import os

OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY')
MAX_TOKENS = 500
QUESTION_CONTEXT_MAX_TOKEN = 1000
OPENAI_COMPLETION_MAX_TOKEN = 1000

OPENAI_API_KEYS = [
    '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',
    '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',
    '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',
    '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',
    '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',
    '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',
    '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',
    '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',
    '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',
    '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',
    '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',
    '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',
    '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',
    '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',
    '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',
    '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',
    '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',
]

OPENAI_API_TIMEOUT = 30

APP_CLIENT_ID = 'pt_ai'
APP_CLIENT_SECRET = 'permission_manage'

DANGQUYUN_IIDENTITY_SERVER = os.environ.get('DANGQUYUN_IIDENTITY_SERVER')
DANGQUYUN_IIDENTITY_SERVER_ISSUER = f'{DANGQUYUN_IIDENTITY_SERVER}/useridentity'
DANGQUYUN_IIDENTITY_SERVER_TOKEN_ENDPOINT = f'{DANGQUYUN_IIDENTITY_SERVER}/useridentity/connect/token'
DANGQUYUN_IIDENTITY_SERVER_AUTH_ENDPOINT = f'{DANGQUYUN_IIDENTITY_SERVER}/useridentity/connect/auth'
DANGQUYUN_IIDENTITY_SERVER_INTROSPECTION_ENDPOINT = f'{DANGQUYUN_IIDENTITY_SERVER}/useridentity/connect/introspect'

OIDC_SCOPES = ["internal_service"]
OIDC_REDIRECT_URI = "http://www.baidu.com"

WEAVIATE_URL = os.environ.get('WEAVIATE_URL')
WEAVIATE_CLASS_PREFIX = 'PtAi'
WEAVIATE_QUERY_NEAR_CERTAINTY = 0.9
WEAVIATE_QUERY_NEAR_LIMIT = 10
